---
title: "viz"
author: "Maria_Król"
date: "9 04 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Wizualizacje na przykładzie województw

1. Pakiet `geogrid` (poligony normalne, heksagonalne, kwadratowe)

```{r}
library(geogrid)
library(sf)
library(tidyverse)
library(sf)
library(tmap)

download.file("https://github.com/bananaonthemoon/wybory/blob/master/dane/prez_woj.gpkg", "prez_woj.gpkg")

prez_woj = read_sf("prez_woj.gpkg", stringsAsFactors=FALSE) 
prez_woj$nazwa4 <- substr(prez_woj$Nazwa, 1, 4)

rawplot <- tm_shape(prez_woj) + 
  tm_polygons("X1_frekw", palette = "viridis") +
  tm_text("nazwa4")


# hex ---------------------------------------------------------------------


par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells <- calculate_grid(shape = prez_woj, grid_type = "hexagonal", seed = i)
  plot(new_cells, main = paste("Seed", i, sep = " "))
}

new_cells_hex <- calculate_grid(shape = prez_woj, grid_type = "hexagonal", seed = 2)
resulthex <- assign_polygons(prez_woj, new_cells_hex)


# reg ---------------------------------------------------------------------


par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells <- calculate_grid(shape = prez_woj, grid_type = "regular", seed = i)
  plot(new_cells, main = paste("Seed", i, sep = " "))
}

new_cells_reg <- calculate_grid(shape = prez_woj, grid_type = "regular", seed = 2)
resultreg <- assign_polygons(prez_woj, new_cells_reg)


# laczenie wizualizacji ---------------------------------------------------

hexplot <- tm_shape(resulthex) + 
  tm_polygons("X1_frekw", palette = "viridis") +
  tm_text("nazwa4")

regplot <- tm_shape(resultreg) + 
  tm_polygons("X1_frekw", palette = "viridis") +
  tm_text("nazwa4")

tmap_arrange(rawplot, hexplot, regplot, nrow = 3)
```
