---
title: "viz_markdown"
author: "Maria_Król"
date: "9 04 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Wizualizacja używając pakietu `geogrid`

```{r geogrid_biblioteki, message=FALSE, warning=FALSE, results=FALSE}

library(geogrid)
library(sf)
library(tidyverse)
library(tmap)
library(tmaptools)

```

### Na przykładzie województw
```{r geogrid_obliczenia_woj cache = TRUE, warning=FALSE, results=FALSE}

prez = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_woj.gpkg"
prez_woj = read_sf(prez, stringsAsFactors=FALSE)

# hexplot -----------------------------------------------------------------

par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells = calculate_grid(shape = prez_woj, grid_type = "hexagonal", seed = i)
  plot(new_cells, main = paste("Seed", i, sep = " "))
}

new_cells_hex_woj = calculate_grid(shape = prez_woj, grid_type = "hexagonal", seed = 2)
resulthex_woj = assign_polygons(prez_woj, new_cells_hex_woj)


# regplot -----------------------------------------------------------------


par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells_woj = calculate_grid(shape = prez_woj, grid_type = "regular", seed = i)
  plot(new_cells_woj, main = paste("Seed", i, sep = " "))
}

new_cells_reg_woj = calculate_grid(shape = prez_woj, grid_type = "regular", seed = 2)
resultreg_woj = assign_polygons(prez_woj, new_cells_reg_woj)


```

```{r geogrid_wojewodztwa}

# rawplot -----------------------------------------------------------------


rawplot_woj_duda = tm_shape(prez_woj) + 
  tm_polygons("t1.duda", palette = get_brewer_pal("Blues"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

rawplot_woj_frek = tm_shape(prez_woj) + 
  tm_polygons("f1", palette = get_brewer_pal("Oranges"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)


# hexplot -----------------------------------------------------------------


hexplot_woj_duda = tm_shape(resulthex_woj) + 
  tm_polygons("t1.duda", palette = get_brewer_pal("Blues"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

hexplot_woj_frek = tm_shape(resulthex_woj) + 
  tm_polygons("f1", palette = get_brewer_pal("Oranges"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)


# regplot -----------------------------------------------------------------


regplot_woj_duda = tm_shape(resultreg_woj) + 
  tm_polygons("t1.duda", palette = get_brewer_pal("Reds"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

regplot_woj_frek = tm_shape(resultreg_woj) + 
  tm_polygons("f1", palette = get_brewer_pal("Oranges"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

# layout -----------------------------------------------------------------

reglayout_woj_duda = tm_shape(resultreg_woj) + tm_polygons("t1.duda", palette = get_brewer_pal("Reds")) +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

reglayout_woj_frek = tm_shape(resultreg_woj) + tm_polygons("f1", palette = get_brewer_pal("Oranges")) +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

```

```{r geogrid_wojewodztwa_wynik, message=FALSE, warning=FALSE}

tmap_arrange(rawplot_woj_duda, hexplot_woj_duda, regplot_woj_duda, reglayout_woj_duda, rawplot_woj_frek, hexplot_woj_frek, regplot_woj_frek, reglayout_woj_frek, nrow = 2)

```

## Na przykładzie powiatów
```{r geogrid_obliczenia_pow cache = TRUE, warning = FALSE, results = FALSE}

prez_pow = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_powiaty.gpkg"
prez_powiaty = read_sf(prez_pow, stringsAsFactors=FALSE)

# hex -----------------------------------------------------------------

par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells = calculate_grid(shape = prez_powiaty, grid_type = "hexagonal", seed = i)
  plot(new_cells, main = paste("Seed", i, sep = " "))
}

new_cells_hex_pow = calculate_grid(shape = prez_powiaty, grid_type = "hexagonal", seed = 2)
resulthex_pow = assign_polygons(prez_powiaty, new_cells_hex_pow)

# reg -----------------------------------------------------------------

par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells = calculate_grid(shape = prez_powiaty, grid_type = "regular", seed = i)
  plot(new_cells, main = paste("Seed", i, sep = " "))
}

new_cells_reg_pow = calculate_grid(shape = prez_powiaty, grid_type = "regular", seed = 2)
resultreg_pow = assign_polygons(prez_powiaty, new_cells_reg_pow)

```

```{r geogrid_powiaty}


# rawplot -----------------------------------------------------------------


rawplot_pow_duda = tm_shape(prez_powiaty) + 
  tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds") , legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

rawplot_pow_frek = tm_shape(prez_powiaty) + 
  tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens") , legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)


# hexplot -----------------------------------------------------------------


hexplot_pow_duda = tm_shape(resulthex_pow) + 
  tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

hexplot_pow_frek = tm_shape(resulthex_pow) + 
  tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)


# regplot -----------------------------------------------------------------


regplot_pow_duda = tm_shape(resultreg_pow) + 
  tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

regplot_pow_frek = tm_shape(resultreg_pow) + 
  tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Greens"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

# layout -----------------------------------------------------------------

layout_pow_duda = tm_shape(resultreg_pow) + tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds")) +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

layout_pow_frek = tm_shape(resultreg_pow) + tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens")) +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

```

```{r geogrid_powiaty_wynik, message=FALSE, warning=FALSE}

tmap_arrange(rawplot_pow_duda, hexplot_pow_duda, regplot_pow_duda, layout_pow_duda, rawplot_pow_frek, hexplot_pow_frek, regplot_pow_frek, layout_pow_frek, nrow = 2)


tmap_save()

```


## Wizualizacja używając pakietu `cartogram`
```{r cartogram_biblioteki, message=FALSE, warning=FALSE}

library(cartogram)
library(tmap)
library(maptools)
library(tidyverse)
library(sf)
library(tmaptools)

```

### Na przykładzie województw
```{r cartogram_wojewodztwa, chunk = TRUE, message=FALSE, warning=FALSE, results=FALSE}

prez_w = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_woj.gpkg"
prez_woj = read_sf(prez_w, stringsAsFactors=FALSE) %>%
  st_transform(crs = 2180)

# Continuous Area Cartogram
prez_woj_cont_duda = cartogram_cont(prez_woj, "t1.duda", 8)
prez_woj_cont_frek = cartogram_cont(prez_woj, "f1", 8)

# Non-contiguous Area Cartogram
prez_woj_ncont_duda = cartogram_ncont(prez_woj, "t1.duda")
prez_woj_ncont_frek = cartogram_ncont(prez_woj, "f1")

# Non-overlapping Circles Cartogram
prez_woj_dorling_duda = cartogram_dorling(prez_woj, "t1.duda")
prez_woj_dorling_frek = cartogram_dorling(prez_woj, "f1")

# Plots
cont_woj_duda = tm_shape(prez_woj_cont_duda) + tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds"), palette = get_brewer_pal("Reds"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

cont_woj_frek = tm_shape(prez_woj_cont_frek) + tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

ncont_woj_duda = tm_shape(prez_woj) + tm_borders() + 
  tm_shape(prez_woj_ncont_duda) + tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

ncont_woj_frek = tm_shape(prez_woj) + tm_borders() + 
  tm_shape(prez_woj_ncont_frek) + tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

dorling_woj_duda = tm_shape(prez_woj) + tm_borders() + 
  tm_shape(prez_woj_dorling_duda) + tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

dorling_woj_frek = tm_shape(prez_woj) + tm_borders() + 
  tm_shape(prez_woj_dorling_frek) + tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

layout_woj_duda = tm_shape(prez_woj_dorling_duda) + tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds")) +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

layout_woj_frek = tm_shape(prez_woj_dorling_frek) + tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens")) +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

```

```{r cartogram_wojewodztwa_wynik, message=FALSE, warning=FALSE}

tmap_arrange(cont_woj_duda, ncont_woj_duda, dorling_woj_duda, layout_woj_duda, cont_woj_frek, ncont_woj_frek, dorling_woj_frek, layout_woj_frek, nrow = 2)

```

```{r cartogram_powiaty, chunk = TRUE, message=FALSE, warning=FALSE, results=FALSE}

prez_p = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_powiaty.gpkg"
prez_pow = read_sf(prez_p, stringsAsFactors=FALSE) %>%
  st_transform(crs = 2180)

# Continuous Area Cartogram
prez_pow_cont_duda = cartogram_cont(prez_woj, "t1.duda", 8)
prez_pow_cont_frek = cartogram_cont(prez_woj, "f1", 8)

# Non-contiguous Area Cartogram
prez_pow_ncont_duda = cartogram_ncont(prez_woj, "t1.duda")
prez_pow_ncont_frek = cartogram_ncont(prez_woj, "f1")

# Non-overlapping Circles Cartogram
prez_pow_dorling_duda = cartogram_dorling(prez_woj, "t1.duda")
prez_pow_dorling_frek = cartogram_dorling(prez_woj, "f1")

# Plots
cont_pow_duda = tm_shape(prez_pow_cont_duda) + tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds"), palette = get_brewer_pal("Reds"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

cont_pow_frek = tm_shape(prez_pow_cont_frek) + tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

ncont_pow_duda = tm_shape(prez_woj) + tm_borders() + 
  tm_shape(prez_pow_ncont_duda) + tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

ncont_pow_frek = tm_shape(prez_woj) + tm_borders() + 
  tm_shape(prez_pow_ncont_frek) + tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

dorling_pow_duda = tm_shape(prez_woj) + tm_borders() + 
  tm_shape(prez_pow_dorling_duda) + tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

dorling_pow_frek = tm_shape(prez_woj) + tm_borders() + 
  tm_shape(prez_pow_dorling_frek) + tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

layout_pow_duda = tm_shape(prez_pow_dorling_duda) + tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds")) +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

layout_pow_frek = tm_shape(prez_pow_dorling_frek) + tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens")) +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

```

```{r cartogram_powiaty_wynik, message=FALSE, warning=FALSE}

tmap_arrange(cont_pow_duda, ncont_pow_duda, dorling_pow_duda, layout_pow_duda, cont_pow_frek, ncont_pow_frek, dorling_pow_frek, layout_pow_frek, nrow = 2)

```