---
title: "viz_markdown"
author: "Maria_Król"
date: "9 04 2020"
output: html_document
---

## Zmienna `t1.duda`

## Wizualizacja używając pakietu `geogrid`

```{r, echo=FALSE}
library(geogrid)
library(sf)
library(tidyverse)
library(tmap)
```

### Na przykładzie województw
```{r}

prez = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_woj.gpkg"
prez_woj = read_sf(prez, stringsAsFactors=FALSE)
prez_woj$Nazwa4 = substr(prez_woj$Nazwa, 1, 4)


# rawplot -----------------------------------------------------------------


rawplot_woj = tm_shape(prez_woj) + 
  tm_polygons("t1.duda", palette = "viridis", legend.show = FALSE) +
  tm_text("Nazwa4") +
  tm_layout(frame = FALSE, legend.outside = TRUE)


# hexplot -----------------------------------------------------------------


par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells = calculate_grid(shape = prez_woj, grid_type = "hexagonal", seed = i)
  plot(new_cells, main = paste("Seed", i, sep = " "))
}

new_cells_hex_woj = calculate_grid(shape = prez_woj, grid_type = "hexagonal", seed = 2)
resulthex_woj = assign_polygons(prez_woj, new_cells_hex_woj)

hexplot_woj = tm_shape(resulthex_woj) + 
  tm_polygons("t1.duda", palette = "viridis", legend.show = FALSE) +
  tm_text("Nazwa4") +
  tm_layout(frame = FALSE, legend.outside = TRUE)


# regplot -----------------------------------------------------------------

par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells_woj = calculate_grid(shape = prez_woj, grid_type = "regular", seed = i)
  plot(new_cells_woj, main = paste("Seed", i, sep = " "))
}

new_cells_reg_woj = calculate_grid(shape = prez_woj, grid_type = "regular", seed = 2)
resultreg_woj = assign_polygons(prez_woj, new_cells_reg_woj)

regplot_woj = tm_shape(resultreg_woj) + 
  tm_polygons("t1.duda", palette = "viridis", legend.show = FALSE) +
  tm_text("Nazwa4") +
  tm_layout(frame = FALSE, legend.outside = TRUE)

reglayout_woj = tm_shape(resultreg_woj) + tm_polygons("t1.duda", palette = "viridis") +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

tmap_arrange(rawplot_woj, hexplot_woj, regplot_woj, reglayout_woj, nrow = 1)

```


### Na przykładzie powiatów
```{r}

prez2 = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_powiaty.gpkg"
prez_powiaty = read_sf(prez2, stringsAsFactors=FALSE) 
prez_powiaty$Nazwa4 = substr(prez_powiaty$Nazwa, 1, 4)


# rawplot -----------------------------------------------------------------


rawplot_pow = tm_shape(prez_powiaty) + 
  tm_polygons("t1.duda", palette = "viridis", legend.show = FALSE) +
  tm_text("Nazwa4") +
  tm_layout(frame = FALSE, legend.outside = TRUE)


# hexplot -----------------------------------------------------------------


par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells = calculate_grid(shape = prez_powiaty, grid_type = "hexagonal", seed = i)
  plot(new_cells, main = paste("Seed", i, sep = " "))
}

new_cells_hex_pow = calculate_grid(shape = prez_powiaty, grid_type = "hexagonal", seed = 2)
resulthex_pow = assign_polygons(prez_powiaty, new_cells_hex_pow)

hexplot_pow = tm_shape(resulthex_pow) + 
  tm_polygons("t1.duda", palette = "viridis", legend.show = FALSE) +
  tm_text("Nazwa4") +
  tm_layout(frame = FALSE, legend.outside = TRUE)


# regplot -----------------------------------------------------------------

par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells = calculate_grid(shape = prez_powiaty, grid_type = "regular", seed = i)
  plot(new_cells, main = paste("Seed", i, sep = " "))
}

new_cells_reg_pow = calculate_grid(shape = prez_powiaty, grid_type = "regular", seed = 2)
resultreg_pow = assign_polygons(prez_powiaty, new_cells_reg_pow)

regplot_pow = tm_shape(resultreg_pow) + 
  tm_polygons("t1.duda", palette = "viridis", legend.show = FALSE) +
  tm_text("Nazwa4") +
  tm_layout(frame = FALSE, legend.outside = TRUE)

reglayout_pow = tm_shape(resultreg_pow) + tm_polygons("t1.duda", palette = "viridis") +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

tmap_arrange(rawplot_pow, hexplot_pow, regplot_pow, reglayout_pow, nrow = 1)

```



## Wizualizacja używając pakietu `cartogram`

```{r}
library(cartogram)
library(tmap)
library(maptools)
library(tidyverse)
library(sf)
```

### Na przykładzie województw
```{r}

prez_w = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_woj.gpkg"
prez_woj = read_sf(prez_w, stringsAsFactors=FALSE) %>%
  st_transform(crs = 2180)

# Continuous Area Cartogram
prez_woj_cont = cartogram_cont(prez_woj, "t1.duda", 8)

# Non-contiguous Area Cartogram
prez_woj_ncont = cartogram_ncont(prez_woj, "t1.duda")

# Non-overlapping Circles Cartogram
prez_woj_dorling = cartogram_dorling(prez_woj, "t1.duda")

# Plots
cont_woj = tm_shape(prez_woj_cont) + tm_polygons("t1.duda", style = "jenks", legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

ncont_woj = tm_shape(prez_woj) + tm_borders() + 
  tm_shape(prez_woj_ncont) + tm_polygons("t1.duda", style = "jenks", legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

dorling_woj = tm_shape(prez_woj) + tm_borders() + 
  tm_shape(prez_woj_dorling) + tm_polygons("t1.duda", style = "jenks", legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

layout_woj = tm_shape(prez_woj_dorling_woj) + tm_polygons("t1.duda", style = "jenks") +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

tmap_arrange(cont_woj, ncont_woj, dorling_woj, layout_woj, nrow = 1)

```


### Na przykładzie powiatów (shp is invalid)
```{r}

prez_p = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_powiaty.gpkg"
prez_powiaty = read_sf(prez_p, stringsAsFactors=FALSE) %>%
  st_transform(crs = 2180)

# Continuous Area Cartogram
prez_powiaty_cont = cartogram_cont(prez_powiaty, "t1.duda", 8)

# Non-contiguous Area Cartogram
prez_powiaty_ncont = cartogram_ncont(prez_powiaty, "t1.duda")

# Non-overlapping Circles Cartogram
prez_powiaty_dorling = cartogram_dorling(prez_powiaty, "t1.duda")

# Plots
cont_pow = tm_shape(prez_powiaty_cont) + tm_polygons("t1.duda", style = "jenks", legend.show = FALSE) +
  tm_layout(frame = FALSE)

ncont_pow = tm_shape(prez_powiaty) + tm_borders() + 
  tm_shape(prez_powiaty_ncont) + tm_polygons("t1.duda", style = "jenks", legend.show = FALSE) +
  tm_layout(frame = FALSE)

dorling_pow = tm_shape(prez_powiaty) + tm_borders() + 
  tm_shape(prez_powiaty_dorling) + tm_polygons("t1.duda", style = "jenks", legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

layout_pow = tm_shape(prez_powiaty_dorling) + tm_polygons("t1.duda", style = "jenks") +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

tmap_arrange(cont_pow, ncont_pow, dorling_pow, layout_pow, nrow = 1)
```

## Wizualizacja używając pakietu `linemap`

### Na przykładzie województw
```{r}
library(sf)
library(tidyverse)
library(linemap)

download.file("https://www.gis-support.pl/downloads/Wojewodztwa.zip", "Wojewodztwa.zip")
unzip("Wojewodztwa.zip")
granice = read_sf("Wojew˘dztwa.shp", stringsAsFactors=FALSE) %>%
  st_transform(crs = 2180) %>%
  st_combine() 

prez = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_woj.gpkg"
prez_woj = read_sf(prez, stringsAsFactors=FALSE) 


# LINEMAP -----------------------------------------------------------------


grid = getgrid(x = prez_woj, cellsize = 4000, var = "t1.duda")


# wizualizacja 1 ------------------------------------------------------------


tlo = par(mar=c(0,0,0,0), bg = "ivory2")
plot(st_geometry(granice), col="ivory1", border = NA,
     xlim = c(min(grid$X), max(grid$X)), ylim= c(min(grid$Y), max(grid$Y)))
linemap(x = grid, var = "t1.duda", k = 200, threshold = 0.00005,
        col = "ivory1", border = "ivory4", lwd = 0.6, add = TRUE)
par(tlo)


# wizualizacja 2 ------------------------------------------------------------

opar = par(mar = c(0,0,0,0))
plot(st_geometry(granice), col="lightblue3", border = NA, bg = "lightblue2",
     xlim = c(min(grid$X), max(grid$X)), ylim= c(min(grid$Y), max(grid$Y)))
linemap(x = grid, var = "t1.duda", k = 5000, threshold = 0.000005,
        col = "lightblue3", border = "white", lwd = 0.6,
        add = TRUE)
par(opar)
```

### Na przykładzie powiatów
```{r}
library(sf)
library(tidyverse)
library(linemap)

download.file("https://www.gis-support.pl/downloads/Powiaty.zip", "Powiaty.zip")
unzip("Powiaty.zip")
granice = read_sf("Powiaty.shp", stringsAsFactors=FALSE) %>%
  st_transform(crs = 2180) %>%
  st_combine() 

prez = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_powiaty.gpkg"
prez_powiaty = read_sf(prez, stringsAsFactors=FALSE) 


# LINEMAP -----------------------------------------------------------------


grid = getgrid(x = prez_powiaty, cellsize = 4000, var = "t1.duda")


# wizualizacja 1 ------------------------------------------------------------


tlo = par(mar=c(0,0,0,0), bg = "ivory2")
plot(st_geometry(granice), col="ivory1", border = NA,
     xlim = c(min(grid$X), max(grid$X)), ylim= c(min(grid$Y), max(grid$Y)))
linemap(x = grid, var = "t1.duda", k = 200, threshold = 0.00005,
        col = "ivory1", border = "ivory4", lwd = 0.6, add = TRUE)
par(tlo)


# wizualizacja 2 ------------------------------------------------------------

opar = par(mar = c(0,0,0,0))
plot(st_geometry(granice), col="lightblue3", border = NA, bg = "lightblue2",
     xlim = c(min(grid$X), max(grid$X)), ylim= c(min(grid$Y), max(grid$Y)))
linemap(x = grid, var = "t1.duda", k = 5000, threshold = 0.000005,
        col = "lightblue3", border = "white", lwd = 0.6,
        add = TRUE)
par(opar)
```
### Na przykładzie gmin
```{r}
library(sf)
library(tidyverse)
library(linemap)

download.file("https://www.gis-support.pl/downloads/Gminy.zip", "Gminy.zip")
unzip("Gminy.zip")
granice = read_sf("Gminy.shp", stringsAsFactors=FALSE) %>%
  st_transform(crs = 2180) %>%
  st_combine() 

prez = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_gminy.gpkg"
prez_gminy = read_sf(prez, stringsAsFactors=FALSE) 


# LINEMAP -----------------------------------------------------------------


grid = getgrid(x = prez_gminy, cellsize = 4000, var = "t1.duda")


# wizualizacja 1 ------------------------------------------------------------


tlo = par(mar=c(0,0,0,0), bg = "ivory2")
plot(st_geometry(granice), col="ivory1", border = NA,
     xlim = c(min(grid$X), max(grid$X)), ylim= c(min(grid$Y), max(grid$Y)))
linemap(x = grid, var = "t1.duda", k = 200, threshold = 0.00005,
        col = "ivory1", border = "ivory4", lwd = 0.6, add = TRUE)
par(tlo)


# wizualizacja 2 ------------------------------------------------------------

opar = par(mar = c(0,0,0,0))
plot(st_geometry(granice), col="lightblue3", border = NA, bg = "lightblue2",
     xlim = c(min(grid$X), max(grid$X)), ylim= c(min(grid$Y), max(grid$Y)))
linemap(x = grid, var = "t1.duda", k = 5000, threshold = 0.000005,
        col = "lightblue3", border = "white", lwd = 0.6,
        add = TRUE)
par(opar)
```



