---
title: "issues"
author: "Maria_Król"
date: "7 05 2020"
output: html_document
---

# problem numero dos

```{r cartogram_wojewodztwa_dane, cache = TRUE, warning = FALSE, results = FALSE}

library(cartogram)
library(tidyverse)
library(sf)

prez_w = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_woj.gpkg"
prez_woj = read_sf(prez_w, stringsAsFactors=FALSE) %>%
  st_transform(crs = 2180)

```

### Błąd w poleceniu 'common_crs(x, y)': coordinate reference systems not equal: use st_transform() first?

```{r cartogram_wojewodztwa_obliczenia, cache = TRUE, warning = FALSE}

# Continuous Area Cartogram
prez_woj_cont_duda = cartogram_cont(prez_woj, "t1.duda", 8)
prez_woj_cont_frek = cartogram_cont(prez_woj, "f1", 8)

# Non-contiguous Area Cartogram
prez_woj_ncont_duda = cartogram_ncont(prez_woj, "t1.duda")
prez_woj_ncont_frek = cartogram_ncont(prez_woj, "f1")

# Non-overlapping Circles Cartogram
prez_woj_dorling_duda = cartogram_dorling(prez_woj, "t1.duda")
prez_woj_dorling_frek = cartogram_dorling(prez_woj, "f1")

```