## Na przykładzie powiatów
```{r geogrid_obliczenia_pow, cache = TRUE, warning = FALSE, results = FALSE}

prez_pow = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_powiaty.gpkg"
prez_powiaty = read_sf(prez_pow, stringsAsFactors=FALSE)

# hex -----------------------------------------------------------------

par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells = calculate_grid(shape = prez_powiaty, grid_type = "hexagonal", seed = i)
  plot(new_cells, main = paste("Seed", i, sep = " "))
}

new_cells_hex_pow = calculate_grid(shape = prez_powiaty, grid_type = "hexagonal", seed = 2)
resulthex_pow = assign_polygons(prez_powiaty, new_cells_hex_pow)

# reg -----------------------------------------------------------------

par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))
for (i in 1:6) {
  new_cells = calculate_grid(shape = prez_powiaty, grid_type = "regular", seed = i)
  plot(new_cells, main = paste("Seed", i, sep = " "))
}

new_cells_reg_pow = calculate_grid(shape = prez_powiaty, grid_type = "regular", seed = 2)
resultreg_pow = assign_polygons(prez_powiaty, new_cells_reg_pow)

```

```{r geogrid_powiaty}


# rawplot -----------------------------------------------------------------

set.seed(64)
rawplot_pow_duda = tm_shape(prez_powiaty) + 
  tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds") , legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

rawplot_pow_frek = tm_shape(prez_powiaty) + 
  tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens") , legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)


# hexplot -----------------------------------------------------------------

set.seed(46)
hexplot_pow_duda = tm_shape(resulthex_pow) + 
  tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

hexplot_pow_frek = tm_shape(resulthex_pow) + 
  tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)


# regplot -----------------------------------------------------------------


regplot_pow_duda = tm_shape(resultreg_pow) + 
  tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

regplot_pow_frek = tm_shape(resultreg_pow) + 
  tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Greens"), legend.show = FALSE) +
  tm_layout(frame = FALSE, legend.outside = TRUE)

# layout -----------------------------------------------------------------

layout_pow_duda = tm_shape(resultreg_pow) + tm_polygons("t1.duda", style = "jenks", palette = get_brewer_pal("Reds")) +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

layout_pow_frek = tm_shape(resultreg_pow) + tm_polygons("f1", style = "jenks", palette = get_brewer_pal("Greens")) +
  tm_layout(frame = FALSE, legend.only = TRUE, legend.position = c("center", "center"))

```

```{r geogrid_powiaty_wynik, message = FALSE, warning = FALSE}

tmap_arrange(rawplot_pow_duda, hexplot_pow_duda, regplot_pow_duda, layout_pow_duda, rawplot_pow_frek, hexplot_pow_frek, regplot_pow_frek, layout_pow_frek, nrow = 2)


```
